### PR TITLE
Allow to set log level via environment variable

### PR DESCRIPTION
**Pull request by omerlh**

### CODE REVIEW

**Comment by adrukh** [comment]
Thanks!

Can you please add a relevant note to the readme?

Also, if I don't have `LOG_LEVEL` in my env, will this setting be skipped? Or does this make `LOG_LEVEL` mandatory? If so, which values should it have?

**Comment by omerlh** [comment]
I would suggest setting it to level of `error` - I was not sure how I can set default value, but that what I will do if I know how. I'll update the readme.

**Comment by omerlh** [comment]
I'm suspecting that fluentd does not write logs because of the following:
```
<match fluent.**>
type null
</match>
```
I'm still thinking what I can do - let me know if you have an idea...

**Comment by adrukh** [comment]
As I understand it,
```
<match fluent.**>
type null
</match>
```
Tells fluentd to ignore its own logs so that it doesn't collapse into recursive logging of its own logging.

What problem are you trying to solve here?

**Comment by omerlh** [comment]
Yeah, I figure that part. I'm trying to understand why we have missing logs on logzio - so I want to look at fluentd logs. I applied this change to our image, but still not logs from fluentd. I guessed this is because it is configured not to write logs - as you mentioned.

**Comment by adrukh** [comment]
I'd debug this directly with `kubectl logs <fluentd-pod>`, kind of hard to debug a problem using the tool you are trying to debug :)

**Comment by omerlh** [comment]
That's a great tip, totally forgot about it....

**Comment by adrukh** [comment]
I'm closing this PR for now, reopen if you think the general use case can be improved?

**Comment by omerlh** [comment]
I think this is still useful - I used it to enable debug logs in my fluentd instance...

**Comment by adrukh** [comment]
Ok, I'm not against it :)

How will it behave if `LOG_LEVEL` is not set in the env?

**Comment by omerlh** [comment]
fluentd will not start...

**Comment by adrukh** [comment]
Any way to make it a non-breaking change? In `bash` it would be something like `${MY_VAR:-MyDefaultValue}`, not sure about this specific format.

Another option is to comment out this portion to the config file, allowing users to opt-in if they wish.

**Pull request closed without merging**
